#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
DEV_DIR="$REPO_ROOT/.dev"

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  echo "OpenPalm Development Setup"
  echo "Usage: ./dev-setup.sh [--clean]"
  exit 0
fi

if [[ "${1:-}" == "--clean" ]]; then
  rm -rf "$DEV_DIR"
  rm -f "$REPO_ROOT/.env"
fi

if [[ ! -f "$REPO_ROOT/.env" ]]; then
  sed "s|/REPLACE/WITH/ABSOLUTE/PATH|$REPO_ROOT|g" "$REPO_ROOT/.env.example" >"$REPO_ROOT/.env"
fi

mkdir -p "$DEV_DIR/data"/{postgres,qdrant,openmemory,assistant,admin}
mkdir -p "$DEV_DIR/config"
mkdir -p "$DEV_DIR/state"/{admin,gateway,postgres,qdrant,openmemory,openmemory-ui,assistant,channel-chat,channel-discord,channel-voice,channel-telegram,automations,rendered/caddy/snippets,caddy/config,caddy/data,logs,tmp}
mkdir -p "$HOME/openpalm"

cp -n "$REPO_ROOT/assets/config/secrets.env" "$DEV_DIR/config/secrets.env" 2>/dev/null || true
cp -n "$REPO_ROOT/assets/config/stack-spec.json" "$DEV_DIR/config/stack-spec.json" 2>/dev/null || true
cp -n "$REPO_ROOT/assets/state/caddy/Caddyfile" "$DEV_DIR/state/rendered/caddy/Caddyfile" 2>/dev/null || true
cat > "$DEV_DIR/state/rendered/caddy/snippets/extra-user-overrides.caddy" <<'EOF'
# user-managed overrides
EOF
for env_name in gateway openmemory postgres qdrant assistant channel-chat channel-discord channel-voice channel-telegram; do
  cat > "$DEV_DIR/state/${env_name}/.env" <<'EOF'
# generated by admin
EOF
done

echo "Dev environment ready under .dev/ and ~/openpalm"
