/**
 * Channel validation, discovery, install, and uninstall for the OpenPalm control plane.
 */
import { mkdirSync, writeFileSync, existsSync, readdirSync, rmSync } from "node:fs";
import type { ChannelInfo } from "./types.js";
import { CORE_SERVICES } from "./types.js";
import { CHANNEL_REGISTRY, REGISTRY_CHANNEL_NAMES, generateChannelCompose } from "./registry.js";
import { randomHex } from "./staging.js";

// ── Channel Name Validation ───────────────────────────────────────────

/** Strict channel name: lowercase alphanumeric + hyphens, 1–63 chars, must start with alnum */
const CHANNEL_NAME_RE = /^[a-z0-9][a-z0-9-]{0,62}$/;

function isValidChannelName(name: string): boolean {
  return CHANNEL_NAME_RE.test(name);
}

// ── Channel Discovery ─────────────────────────────────────────────────

/**
 * Discover installed channels by scanning CONFIG_HOME/channels/.
 *
 * A channel is any .yml file in the channels directory.
 * A .caddy file is optional — if present, the channel gets Caddy HTTP routing.
 * A .env file is optional — contains channel-specific env vars.
 * If absent, the channel is only accessible on the Docker network (host + containers).
 */
export function discoverChannels(configDir: string): ChannelInfo[] {
  const channelsDir = `${configDir}/channels`;
  if (!existsSync(channelsDir)) return [];

  const files = readdirSync(channelsDir);
  const ymlFiles = files.filter((f) => f.endsWith(".yml"));
  const caddyFiles = new Set(files.filter((f) => f.endsWith(".caddy")));
  const envFiles = new Set(files.filter((f) => f.endsWith(".env")));

  return ymlFiles
    .map((ymlFile) => {
      const name = ymlFile.replace(/\.yml$/, "");
      const caddyFile = `${name}.caddy`;
      const envFile = `${name}.env`;
      const hasCaddy = caddyFiles.has(caddyFile);
      const hasEnv = envFiles.has(envFile);
      const registryEntry = CHANNEL_REGISTRY[name];
      return {
        name,
        hasRoute: hasCaddy,
        ymlPath: `${channelsDir}/${ymlFile}`,
        caddyPath: hasCaddy ? `${channelsDir}/${caddyFile}` : null,
        envPath: hasEnv ? `${channelsDir}/${envFile}` : null,
        package: registryEntry?.package,
        customImage: registryEntry?.image,
      };
    })
    .filter((ch) => isValidChannelName(ch.name));
}

// ── Allowlist Checks ───────────────────────────────────────────────────

/**
 * Check if a service name is allowed. Core services are always allowed.
 * Channel services (channel-*) are allowed if a corresponding staged .yml exists
 * in STATE_HOME/artifacts/channels/.
 */
export function isAllowedService(value: string, stateDir?: string): boolean {
  if (!value || !value.trim() || value !== value.toLowerCase()) return false;
  if ((CORE_SERVICES as string[]).includes(value)) return true;
  if (value.startsWith("channel-")) {
    const ch = value.slice("channel-".length);
    if (!isValidChannelName(ch)) return false;
    if (stateDir) {
      return existsSync(`${stateDir}/artifacts/channels/${ch}.yml`);
    }
  }
  return false;
}

/**
 * Check if a channel name is valid. Accepts any channel with a staged
 * .yml file in STATE_HOME/artifacts/channels/.
 */
export function isValidChannel(value: string, stateDir?: string): boolean {
  if (!value || !value.trim()) return false;
  if (!isValidChannelName(value)) return false;
  if (stateDir) {
    return existsSync(`${stateDir}/artifacts/channels/${value}.yml`);
  }
  return false;
}

// ── Channel Install / Uninstall ─────────────────────────────────────────

/**
 * Install a channel from the registry catalog into CONFIG_HOME/channels/.
 * Generates the compose overlay from registry metadata, creates a per-channel
 * .env file with an auto-generated HMAC secret, and writes optional .caddy route.
 * Refuses if the channel is already installed (files already exist).
 */
export function installChannelFromRegistry(
  name: string,
  configDir: string
): { ok: true } | { ok: false; error: string } {
  if (!isValidChannelName(name)) {
    return { ok: false, error: `Invalid channel name: ${name}` };
  }
  if (!(name in CHANNEL_REGISTRY)) {
    return { ok: false, error: `Channel "${name}" not found in registry` };
  }
  const channelsDir = `${configDir}/channels`;
  mkdirSync(channelsDir, { recursive: true });

  const ymlPath = `${channelsDir}/${name}.yml`;
  if (existsSync(ymlPath)) {
    return { ok: false, error: `Channel "${name}" is already installed` };
  }

  const entry = CHANNEL_REGISTRY[name];

  // Generate compose overlay from registry metadata
  const composeYml = generateChannelCompose(name, entry, configDir);
  writeFileSync(ymlPath, composeYml);

  // Generate Caddy route if defined
  if (entry.caddy) {
    writeFileSync(`${channelsDir}/${name}.caddy`, entry.caddy);
  }

  // Create per-channel .env file with auto-generated HMAC secret
  const secretKey = `CHANNEL_${name.toUpperCase().replace(/-/g, "_")}_SECRET`;
  const envLines: string[] = [
    `# Channel: ${name}`,
    `# Auto-generated by OpenPalm. Edit to configure channel-specific settings.`,
    `${secretKey}=${randomHex(16)}`,
  ];
  // Add empty placeholders for other env vars
  for (const v of entry.envVars) {
    if (v !== secretKey) {
      envLines.push(`${v}=`);
    }
  }
  writeFileSync(`${channelsDir}/${name}.env`, envLines.join("\n") + "\n");

  return { ok: true };
}

/**
 * Uninstall a channel by removing its .yml, .caddy, and .env from CONFIG_HOME/channels/.
 */
export function uninstallChannel(
  name: string,
  configDir: string
): { ok: true } | { ok: false; error: string } {
  if (!isValidChannelName(name)) {
    return { ok: false, error: `Invalid channel name: ${name}` };
  }
  const channelsDir = `${configDir}/channels`;
  const ymlPath = `${channelsDir}/${name}.yml`;
  if (!existsSync(ymlPath)) {
    return { ok: false, error: `Channel "${name}" is not installed` };
  }

  rmSync(ymlPath, { force: true });
  rmSync(`${channelsDir}/${name}.caddy`, { force: true });
  rmSync(`${channelsDir}/${name}.env`, { force: true });
  return { ok: true };
}
