import { bindUiEvents } from './ui.js';
import { bindRuntimeEvents } from './runtime.js';
import { bindAccessEvents } from './access.js';
import { bindConnectionsEvents } from './connections.js';
import { bindProvidersEvents } from './providers.js';
import { bindBackupEvents } from './backup.js';
import { bindConfigurationEvents } from './configuration.js';
import { bindPreferencesEvents } from './preferences.js';
import { bindRemoteEvents } from './remote.js';
import { refresh } from './snapshot.js';
import { state } from './state.js';

state.api = window.openpalmAdmin;
bindUiEvents();
bindRuntimeEvents();
bindAccessEvents();
bindConnectionsEvents();
bindProvidersEvents();
bindBackupEvents();
bindConfigurationEvents();
bindPreferencesEvents();
bindRemoteEvents();
void refresh(false);
