#!/usr/bin/env bash
set -euo pipefail

PORT="${OPENCODE_PORT:-4096}"
ENABLE_SSH="${OPENCODE_ENABLE_SSH:-0}"
TARGET_UID="${OP_UID:-1000}"
TARGET_GID="${OP_GID:-1000}"
IS_ROOT=$([ "$(id -u)" = "0" ] && echo 1 || echo 0)

maybe_adjust_uid_gid() {
  # Only when running as root (first entrypoint before gosu).
  if [ "$IS_ROOT" = "0" ]; then return 0; fi

  local current_uid current_gid
  current_uid="$(id -u opencode 2>/dev/null || echo 1000)"
  current_gid="$(id -g opencode 2>/dev/null || echo 1000)"

  if [ "$current_gid" != "$TARGET_GID" ]; then
    groupmod -g "$TARGET_GID" opencode 2>/dev/null || true
  fi
  if [ "$current_uid" != "$TARGET_UID" ]; then
    usermod -u "$TARGET_UID" -g "$TARGET_GID" opencode 2>/dev/null || true
  fi
}

ensure_home_layout() {
  # Create directories that may not exist on first run inside bind-mounted
  # /home/opencode (which shadows whatever was baked into the Dockerfile).
  mkdir -p \
    /home/opencode \
    /home/opencode/.cache \
    /home/opencode/.cache/opencode \
    /home/opencode/.config/opencode \
    /home/opencode/.local/bin \
    /home/opencode/.local/state/opencode \
    /home/opencode/.local/share/opencode \
    /work

  if [ "$IS_ROOT" = "1" ]; then
    # Recursively fix ownership. Previous container runs may have created
    # directories as root when OP_UID/OP_GID differed. A targeted chown
    # misses nested dirs created by third-party tools between invocations.
    chown -R "$TARGET_UID:$TARGET_GID" /home/opencode 2>/dev/null || true

    mkdir -p /var/run/sshd
  fi
}

maybe_enable_ssh() {
  if [ "$ENABLE_SSH" != "1" ] && [ "$ENABLE_SSH" != "true" ]; then
    return 0
  fi

  mkdir -p /var/run/sshd /home/opencode/.ssh
  touch /home/opencode/.ssh/authorized_keys
  chown -R "$TARGET_UID:$TARGET_GID" /home/opencode/.ssh 2>/dev/null || true
  chmod 700 /home/opencode/.ssh
  chmod 600 /home/opencode/.ssh/authorized_keys 2>/dev/null || true

  if [ "$IS_ROOT" = "1" ] && [ ! -f /etc/ssh/sshd_config ]; then
    return 0
  fi

  if [ "$IS_ROOT" = "1" ]; then
    ssh-keygen -A 2>/dev/null || true
    /usr/sbin/sshd 2>/dev/null || true
  fi
}

maybe_source_akm_user_vault() {
  # Source the akm vault:user env file so secrets land in the process
  # environment. Must run before start_cron so vault keys appear in the
  # crontab preamble. Only possible as root (vault file is 0600).
  if [ "$IS_ROOT" = "0" ]; then return 0; fi

  local vault_path=""
  if [ -n "${AKM_STASH_DIR:-}" ] && [ -f "${AKM_STASH_DIR}/vaults/user.env" ]; then
    vault_path="${AKM_STASH_DIR}/vaults/user.env"
  elif [ -f "/etc/vault/user.env" ]; then
    vault_path="/etc/vault/user.env"
  fi

  if [ -z "$vault_path" ]; then return 0; fi

  set +a
  # shellcheck disable=SC1090
  . "$vault_path"
  set +a
}

seed_default_agents_md() {
  local src="/usr/local/share/openpalm/AGENTS.md"
  local dest="${OPENCODE_CONFIG_DIR:-/etc/openpalm/assistant}/AGENTS.md"
  [ -f "$src" ] && [ ! -f "$dest" ] && cp "$src" "$dest" 2>/dev/null || true
}

start_cron_and_sync_tasks() {
  # Build a crontab preamble with environment variables and vault keys
  # so cron jobs inherit the same secrets as the main process.
  local crontab_file="/tmp/crontab"
  echo "# Auto-generated by entrypoint — do not edit" > "$crontab_file"
  echo "SHELL=/bin/bash" >> "$crontab_file"
  echo "PATH=/usr/local/bin:/usr/bin:/bin:/opt/persistent/bin" >> "$crontab_file"

  # Forward selected env vars into cron jobs
  for var in HOME AKM_STASH_DIR AKM_CONFIG_DIR AKM_DATA_DIR AKM_STATE_DIR AKM_CACHE_DIR \
             OPENCODE_API_URL OPENCODE_CONFIG_DIR OP_HOME; do
    if [ -n "${!var:-}" ]; then
      echo "export $var=\"${!var}\"" >> "$crontab_file"
    fi
  done

  # Forward vault keys (already sourced into env by maybe_source_akm_user_vault)
  if [ -n "${VAULT_KEYS_EXPORTED:-}" ]; then
    echo "export VAULT_KEYS_EXPORTED=\"$VAULT_KEYS_EXPORTED\"" >> "$crontab_file"
  fi

  # Sync automation tasks from the akm stash into cron, then start cron
  local tasks_dir="${AKM_STASH_DIR:-/akm}/tasks"
  if command -v akm >/dev/null 2>&1 && [ -d "$tasks_dir" ]; then
    akm tasks sync 2>/dev/null || true
  fi

  # Install crontab if there are any cron entries (akm tasks sync adds them)
  if [ -f "$crontab_file" ]; then
    crontab "$crontab_file" 2>/dev/null || true
    rm -f "$crontab_file"
    cron 2>/dev/null || true
  fi

  # Background re-sync loop: picks up task file changes without restart
  (
    while true; do
      sleep 60
      if command -v akm >/dev/null 2>&1 && [ -d "$tasks_dir" ]; then
        akm tasks sync 2>/dev/null || true
      fi
    done
  ) &
}

start_opencode() {
  cd /work

  # Ensure bun's user-writable directories exist (set via Dockerfile ENV).
  mkdir -p "${BUN_INSTALL:-/home/opencode/.bun}/bin" \
           "${BUN_INSTALL_CACHE_DIR:-/home/opencode/.cache/bun/install}"

  # Fix ownership of bun dirs if we're still root (before gosu).
  if [ "$IS_ROOT" = "1" ]; then
    chown -R "$TARGET_UID:$TARGET_GID" \
      "${BUN_INSTALL:-/home/opencode/.bun}" \
      "${BUN_INSTALL_CACHE_DIR:-/home/opencode/.cache/bun}" \
      2>/dev/null || true
  fi

  local cmd=(opencode web --hostname 0.0.0.0 --port "$PORT" --print-logs)
  if [ "$IS_ROOT" = "1" ]; then
    if ! command -v gosu >/dev/null 2>&1; then
      echo "ERROR: gosu not found — cannot drop privileges. Install gosu in the Dockerfile." >&2
      exit 1
    fi
    export HOME=/home/opencode
    cmd=(gosu opencode env HOME=/home/opencode "${cmd[@]}")
  fi

  exec "${cmd[@]}"
}

maybe_adjust_uid_gid
ensure_home_layout
maybe_enable_ssh
maybe_source_akm_user_vault
seed_default_agents_md
start_cron_and_sync_tasks
start_opencode
