#!/usr/bin/env bash
set -euo pipefail

# Assistant-only Debian cron matrix. Every host path and Compose project is
# generated by this process; cleanup rejects paths outside the guarded prefix.
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# shellcheck source=scripts/rootless-smoke-fixture.sh
source "${ROOT_DIR}/scripts/rootless-smoke-fixture.sh"

SYSTEM_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
EXPECTED_AKM_VERSION='0.9.0-rc.15'
COMPOSE_COMMAND_TIMEOUT_SECONDS=90
PROBE_HOST_TIMEOUT_SECONDS=9
PROBE_CONTAINER_TIMEOUT_SECONDS=8
RUNTIME_READY_TIMEOUT_SECONDS=180
BACKGROUND_SYNC_TIMEOUT_SECONDS=130
STALE_HEALTH_TIMEOUT_SECONDS=110
HEALTH_RECOVERY_TIMEOUT_SECONDS=75
CRON_EXECUTION_TIMEOUT_SECONDS=90
FILE_CONTENT_TIMEOUT_SECONDS=30
SMOKE_ROOT="$(smoke_guarded_home "$ROOT_DIR" \
  "${OP_DEBIAN_CRON_SMOKE_HOME:-${ROOT_DIR}/.debian-cron-smoke-$$}" \
  '.debian-cron-smoke' OP_DEBIAN_CRON_SMOKE_HOME)"
if [[ -e "$SMOKE_ROOT" || -L "$SMOKE_ROOT" ]]; then
  echo "Refusing to replace an existing smoke path: $SMOKE_ROOT" >&2
  exit 1
fi

declare -a SMOKE_HOMES=()
declare -a SMOKE_PROJECTS=()
SMOKE_ROOT_CREATED=0
SMOKE_COMPLETED=0
STARTED_CONTAINER=''

cron_compose() {
  local home="$1"
  local project="$2"
  shift 2
  timeout "${COMPOSE_COMMAND_TIMEOUT_SECONDS}s" docker compose --project-directory "$ROOT_DIR" \
    -f "$home/system/stack/core.compose.yml" \
    -f "$home/assistant-only.compose.yml" \
    --env-file "$home/state/stack.env" \
    --project-name "$project" "$@"
}

cleanup() {
  local status=$?
  local index home project cleanup_output
  local cleanup_failed=0
  local projects_clear=1
  trap - EXIT
  set +e
  for index in "${!SMOKE_HOMES[@]}"; do
    home="${SMOKE_HOMES[$index]}"
    project="${SMOKE_PROJECTS[$index]}"
    if ! cleanup_output="$(
      timeout 20s docker compose --project-directory "$ROOT_DIR" \
        -f "$home/system/stack/core.compose.yml" \
        -f "$home/assistant-only.compose.yml" \
        --env-file "$home/state/stack.env" \
        --project-name "$project" down --remove-orphans --volumes 2>&1
    )"; then
      echo "cleanup: compose down failed for project $project" >&2
      [[ -z "$cleanup_output" ]] || printf '%s\n' "$cleanup_output" >&2
      cleanup_failed=1
    fi
    if ! smoke_remove_project_resources "$project"; then
      echo "cleanup: force-removal failed for project $project" >&2
      cleanup_failed=1
    fi
    if ! smoke_verify_project_clear "$project"; then
      projects_clear=0
      cleanup_failed=1
    fi
  done
  if [[ "$SMOKE_ROOT_CREATED" == "1" && "$projects_clear" == "1" ]]; then
    smoke_remove_guarded_home "$ROOT_DIR" "$SMOKE_ROOT" '.debian-cron-smoke' || cleanup_failed=1
  elif [[ "$SMOKE_ROOT_CREATED" == "1" ]]; then
    echo "cleanup: retaining $SMOKE_ROOT because Docker resources could not be proven absent" >&2
  fi
  if [[ "$cleanup_failed" == "1" && "$status" == "0" ]]; then
    status=1
  fi
  if [[ "$status" == "0" && "$SMOKE_COMPLETED" == "1" ]]; then
    echo 'Debian cron behavior smoke passed for identities 2001:2002 and 1000:1000 plus pre-0.9 migration 2003:2004.'
  fi
  exit "$status"
}
trap cleanup EXIT

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

write_task() {
  local container="$1"
  local name="$2"
  [[ "$name" =~ ^[a-z0-9-]+\.yml$ ]] || fail "unsafe smoke task name: $name"
  timeout 15s docker exec --interactive --user node "$container" /bin/bash -c '
    set -euo pipefail
    umask 077
    target="/stash/tasks/$1"
    temporary="${target}.tmp"
    /bin/cat > "$temporary"
    /bin/mv "$temporary" "$target"
  ' _ "$name"
}

delete_task() {
  local container="$1"
  local name="$2"
  [[ "$name" =~ ^[a-z0-9-]+\.yml$ ]] || fail "unsafe smoke task name: $name"
  timeout 10s docker exec --user node "$container" /bin/rm -f -- "/stash/tasks/$name"
}

assistant_identity_values() {
  local container="$1"
  local primary_gid group_record crontab_gid
  primary_gid="$(timeout 5s docker exec --user root "$container" /usr/bin/id -g node)"
  group_record="$(timeout 5s docker exec --user root "$container" /usr/bin/getent group crontab)"
  IFS=: read -r _ _ crontab_gid _ <<<"$group_record"
  [[ "$primary_gid" =~ ^[1-9][0-9]*$ && "$crontab_gid" =~ ^[1-9][0-9]*$ ]] ||
    fail "could not resolve Assistant runtime groups"
  printf '%s:%s\n' "$primary_gid" "$crontab_gid"
}

run_task_sync() {
  local container="$1"
  local values primary_gid crontab_gid
  values="$(assistant_identity_values "$container")"
  primary_gid="${values%%:*}"
  crontab_gid="${values##*:}"
  timeout 65s docker exec --user root "$container" /usr/bin/setpriv \
    --reuid=node --regid="$primary_gid" --groups="$crontab_gid" \
    --bounding-set=-all --inh-caps=-all --ambient-caps=-all --no-new-privs -- \
    /usr/bin/env -u OPENCODE_SERVER_PASSWORD \
    HOME=/home/opencode USER=node LOGNAME=node SHELL=/bin/bash PATH="$SYSTEM_PATH" \
    /usr/local/bin/opencode-entrypoint.sh --sync-once >/dev/null ||
    fail "one-shot task reconciliation failed"
}

read_crontab() {
  timeout 5s docker exec --user root "$1" /usr/bin/crontab -u node -l
}

task_body() {
  local crontab="$1"
  local id="$2"
  local line body=''
  local inside=0
  local begin_count=0
  local end_count=0
  local body_lines=0
  while IFS= read -r line; do
    if [[ "$line" == "# akm:task $id BEGIN" ]]; then
      ((begin_count += 1))
      [[ "$inside" == "0" ]] || return 1
      inside=1
      continue
    fi
    if [[ "$line" == "# akm:task $id END" ]]; then
      ((end_count += 1))
      [[ "$inside" == "1" ]] || return 1
      inside=0
      continue
    fi
    if [[ "$inside" == "1" ]]; then
      ((body_lines += 1))
      body="$line"
    fi
  done <<<"$crontab"
  [[ "$inside" == "0" && "$begin_count" == "1" && "$end_count" == "1" && "$body_lines" == "1" ]] ||
    return 1
  printf '%s\n' "$body"
}

task_binding_matches() {
  local crontab="$1"
  local id="$2"
  local schedule="$3"
  local enabled="$4"
  local body line
  local -a fields=()
  local -a schedule_fields=()
  body="$(task_body "$crontab" "$id")" || return 1
  line="$body"
  if [[ "$enabled" == "true" ]]; then
    [[ "$line" != '# akm:disabled '* ]] || return 1
  else
    [[ "$line" == '# akm:disabled '* ]] || return 1
    line="${line#\# akm:disabled }"
  fi
  read -r -a fields <<<"$line"
  read -r -a schedule_fields <<<"$schedule"
  [[ "${#schedule_fields[@]}" == "5" && "${#fields[@]}" == "16" ]] || return 1
  local index
  for index in 0 1 2 3 4; do
    [[ "${fields[$index]}" == "${schedule_fields[$index]}" ]] || return 1
  done
  [[ "${fields[5]}" == '/usr/local/bin/node' ]] || return 1
  [[ "${fields[6]}" == '/usr/local/lib/node_modules/akm-cli/dist/akm' ]] || return 1
  [[ "${fields[7]}" == '--scheduler-context' ]] || return 1
  [[ "${fields[8]}" =~ ^/opt/akm/data/tasks/context/[0-9a-f]{64}\.json$ ]] || return 1
  [[ "${fields[9]}" == 'task' && "${fields[10]}" == 'run' && "${fields[11]}" == "$id" ]] || return 1
  [[ "${fields[12]}" == '--scheduled' && "${fields[13]}" == '>>' ]] || return 1
  [[ "${fields[14]}" == "/opt/akm/cache/tasks/logs/${id}.log" && "${fields[15]}" == '2>&1' ]] || return 1
}

assert_task_binding() {
  local container="$1"
  local id="$2"
  local schedule="$3"
  local enabled="$4"
  local crontab
  crontab="$(read_crontab "$container")" || fail "could not read native crontab for task $id"
  if ! task_binding_matches "$crontab" "$id" "$schedule" "$enabled"; then
    printf '%s\n' "$crontab" >&2
    fail "task $id does not have exactly one complete expected native binding"
  fi
}

assert_task_absent() {
  local container="$1"
  local id="$2"
  local crontab line
  crontab="$(read_crontab "$container")" || fail "could not read native crontab while checking task $id"
  while IFS= read -r line; do
    if [[ "$line" == "# akm:task $id BEGIN" || "$line" == "# akm:task $id END" ]]; then
      fail "native crontab retained a marker for deleted task $id"
    fi
  done <<<"$crontab"
}

wait_for_task_binding() {
  local container="$1"
  local id="$2"
  local schedule="$3"
  local enabled="$4"
  local timeout_seconds="${5:-$BACKGROUND_SYNC_TIMEOUT_SECONDS}"
  local deadline=$((SECONDS + timeout_seconds))
  local crontab=''
  while ((SECONDS < deadline)); do
    if crontab="$(read_crontab "$container" 2>/dev/null)" &&
      task_binding_matches "$crontab" "$id" "$schedule" "$enabled"; then
      return 0
    fi
    sleep 2
  done
  [[ -z "$crontab" ]] || printf '%s\n' "$crontab" >&2
  fail "timed out waiting for the background reconciler to bind task $id"
}

wait_for_task_absent() {
  local container="$1"
  local id="$2"
  local timeout_seconds="${3:-$BACKGROUND_SYNC_TIMEOUT_SECONDS}"
  local deadline=$((SECONDS + timeout_seconds))
  local crontab line found
  while ((SECONDS < deadline)); do
    found=0
    if crontab="$(read_crontab "$container" 2>/dev/null)"; then
      while IFS= read -r line; do
        if [[ "$line" == "# akm:task $id BEGIN" || "$line" == "# akm:task $id END" ]]; then
          found=1
          break
        fi
      done <<<"$crontab"
      [[ "$found" == "0" ]] && return 0
    fi
    sleep 2
  done
  fail "timed out waiting for the background reconciler to remove task $id"
}

health_command() {
  timeout 5s docker inspect --format '{{json .Config.Healthcheck.Test}}' "$1" |
    jq -er 'if .[0] == "CMD-SHELL" and (length == 2) then .[1] else error("expected CMD-SHELL healthcheck") end'
}

image_health_command() {
  local image
  image="$(timeout 5s docker inspect --format '{{.Image}}' "$1")" || return 1
  timeout 5s docker image inspect --format '{{json .Config.Healthcheck.Test}}' "$image" |
    jq -er 'if .[0] == "CMD-SHELL" and (length == 2) then .[1] else error("expected image CMD-SHELL healthcheck") end'
}

run_health_probe() {
  local command
  command="$(health_command "$1")" || return 1
  timeout "${PROBE_HOST_TIMEOUT_SECONDS}s" docker exec "$1" \
    /usr/bin/timeout --signal=TERM --kill-after=1s "${PROBE_CONTAINER_TIMEOUT_SECONDS}s" \
    /bin/sh -c "$command" >/dev/null 2>&1
}

run_image_health_probe() {
  local command
  command="$(image_health_command "$1")" || return 1
  timeout "${PROBE_HOST_TIMEOUT_SECONDS}s" docker exec "$1" \
    /usr/bin/timeout --signal=TERM --kill-after=1s "${PROBE_CONTAINER_TIMEOUT_SECONDS}s" \
    /bin/sh -c "$command" >/dev/null 2>&1
}

wait_for_health_probe_failure() {
  local container="$1"
  local timeout_seconds="$2"
  local deadline=$((SECONDS + timeout_seconds))
  while ((SECONDS < deadline)); do
    if ! run_health_probe "$container"; then return 0; fi
    sleep 2
  done
  return 1
}

wait_for_health_probe_success() {
  local container="$1"
  local timeout_seconds="$2"
  local deadline=$((SECONDS + timeout_seconds))
  while ((SECONDS < deadline)); do
    if run_health_probe "$container"; then return 0; fi
    sleep 2
  done
  return 1
}

run_application_probe() {
  timeout "${PROBE_HOST_TIMEOUT_SECONDS}s" docker exec "$1" \
    /usr/bin/timeout --signal=TERM --kill-after=1s "${PROBE_CONTAINER_TIMEOUT_SECONDS}s" \
    /bin/sh -c '
    test -r /run/openpalm/cron.pid
    kill -0 "$(cat /run/openpalm/cron.pid)"
    curl -sf http://localhost:4096/health >/dev/null
    curl -sf http://localhost:3000/health >/dev/null
  ' >/dev/null 2>&1
}

wait_for_runtime() {
  local home="$1"
  local project="$2"
  local container="$3"
  local failure_message="${4:-Assistant runtime did not pass its health probe}"
  local diagnostic_pattern="${5:-}"
  local diagnostic_message="${6:-$failure_message}"
  local diagnostic_logs=''
  local attempts=0
  local deadline=$((SECONDS + RUNTIME_READY_TIMEOUT_SECONDS))
  while ((SECONDS < deadline)); do
    if run_health_probe "$container"; then
      return 0
    fi
    ((attempts += 1))
    if [[ -n "$diagnostic_pattern" && $((attempts % 5)) == 0 ]]; then
      diagnostic_logs="$(timeout 5s docker logs --tail 80 "$container" 2>&1 || true)"
      if [[ "$diagnostic_logs" == *"$diagnostic_pattern"* ]]; then
        printf '%s\n' "$diagnostic_logs" >&2
        fail "$diagnostic_message"
      fi
    fi
    sleep 2
  done
  cron_compose "$home" "$project" logs assistant --tail 120 >&2 || true
  fail "$failure_message"
}

wait_for_application_runtime() {
  local home="$1"
  local project="$2"
  local container="$3"
  local deadline=$((SECONDS + RUNTIME_READY_TIMEOUT_SECONDS))
  while ((SECONDS < deadline)); do
    if run_application_probe "$container"; then
      return 0
    fi
    sleep 2
  done
  cron_compose "$home" "$project" logs assistant --tail 120 >&2 || true
  fail "Assistant application processes did not become ready"
}

wait_for_sync_status() {
  local container="$1"
  local expected="$2"
  local timeout_seconds="${3:-$BACKGROUND_SYNC_TIMEOUT_SECONDS}"
  local deadline=$((SECONDS + timeout_seconds))
  local status=''
  local value=''
  while ((SECONDS < deadline)); do
    value="$(timeout 5s docker exec "$container" /usr/bin/timeout 4s \
      /bin/sh -c 'cat /run/openpalm/task-sync.status 2>/dev/null' || true)"
    status="${value%% *}"
    if [[ "$status" == "$expected" && "$value" =~ ^(healthy|degraded)\ [1-9][0-9]*\ (ok|skipped|exit-[0-9]{1,3})$ ]]; then
      return 0
    fi
    sleep 2
  done
  fail "task reconciliation status did not become $expected before the deadline (last value: ${value:-missing})"
}

wait_for_file_content() {
  local path="$1"
  local expected="$2"
  local timeout_seconds="${3:-$FILE_CONTENT_TIMEOUT_SECONDS}"
  local deadline=$((SECONDS + timeout_seconds))
  local actual=''
  while ((SECONDS < deadline)); do
    if [[ -f "$path" ]] && actual="$(<"$path")" && [[ "$actual" == "$expected" ]]; then
      return 0
    fi
    sleep 1
  done
  fail "timed out waiting for smoke artifact $path to contain the expected value (last value: ${actual:-missing})"
}

assert_runtime_identity() {
  local container="$1"
  local uid="$2"
  local gid="$3"
  local task_sync_status
  [[ "$(timeout 5s docker exec --user root "$container" /usr/bin/id -u node)" == "$uid" ]] ||
    fail "node UID does not equal deterministic fixture UID $uid"
  [[ "$(timeout 5s docker exec --user root "$container" /usr/bin/id -g node)" == "$gid" ]] ||
    fail "node GID does not equal deterministic fixture GID $gid"
  [[ "$(timeout 5s docker exec --user root "$container" /usr/bin/stat -c %u /var/spool/cron/crontabs/node)" == "$uid" ]] ||
    fail "native crontab UID does not equal $uid"
  [[ "$(timeout 5s docker exec --user root "$container" /usr/bin/stat -c %g /var/spool/cron/crontabs/node)" == "$gid" ]] ||
    fail "native crontab GID does not equal $gid"
  [[ "$(timeout 5s docker exec --user root "$container" /usr/bin/stat -c %U:%G:%a /run/openpalm/task-sync.status)" == 'root:root:644' ]] ||
    fail "task reconciliation status is not root-owned mode 0644"
  task_sync_status="$(timeout 5s docker exec --user root "$container" /bin/cat /run/openpalm/task-sync.status)"
  [[ "$task_sync_status" =~ ^(healthy|degraded)\ [1-9][0-9]*\ (ok|skipped|exit-[0-9]{1,3})$ ]] ||
    fail "task reconciliation status does not contain a canonical root timestamp"
}

assign_fixture_identity() {
  local home="$1"
  local uid="$2"
  local gid="$3"
  timeout 30s docker run --rm -v "$home:/smoke-home" alpine sh -eu -c '
    case "$1:$2" in
      *[!0-9:]*|:*|*:) exit 64 ;;
    esac
    for path in \
      /smoke-home/data/assistant \
      /smoke-home/cache/assistant \
      /smoke-home/config/assistant \
      /smoke-home/system/assistant \
      /smoke-home/knowledge \
      /smoke-home/config/akm \
      /smoke-home/data/akm \
      /smoke-home/workspace; do
      chown -R "$1:$2" "$path"
    done
    chown "$1:$2" \
      /smoke-home/private/secrets/op_opencode_password \
      /smoke-home/private/secrets/op_ui_login_password
    chmod 0711 /smoke-home/knowledge/secrets
  ' _ "$uid" "$gid"
}

prepare_fixture() {
  local uid="$1"
  local gid="$2"
  local home="${SMOKE_ROOT}/uid-${uid}"
  local project_prefix="openpalm-debian-cron-${uid}"
  local project
  project="$(smoke_guarded_project "${project_prefix}-$$" "$project_prefix" 'generated cron smoke project')"
  smoke_assert_project_absent "$project"

  smoke_copy_skeleton "$home"
  smoke_write_stack_env "$home" "$(smoke_platform_version)" \
    48110 48100 48130 48131 48120 48121 "$uid" "$gid"
  smoke_seed_secrets "$home" 'debian-cron-smoke-password'
  smoke_ensure_home_dirs "$home"

  printf '%s\n' 'OPENPALM_CRON_ENV_LEAK_CANARY=must-stay-scoped' >"$home/knowledge/env/user.env"
  chmod 600 "$home/knowledge/env/user.env"
  # This canary must be launched by Debian cron itself. Its atomic result records
  # the complete scheduled-process privilege and environment boundary.
  cat >"$home/knowledge/tasks/cron-binding.yml" <<'EOF'
version: 2
schedule: '* * * * *'
enabled: true
command:
  - /bin/sh
  - -c
  - |
    set -eu
    if [ "${OPENPALM_CRON_ENV_LEAK_CANARY+x}" = x ]; then
      env_scope=leaked
    else
      env_scope=absent
    fi
    result=/work/cron-binding-result
    temporary="${result}.$$"
    umask 022
    printf 'uid=%s\ngid=%s\ngroups=%s\nno_new_privs=%s\ncap_eff=%s\napprise=%s\nenv_scope=%s\n' \
      "$(id -u)" \
      "$(id -g)" \
      "$(id -G | tr ' ' ',')" \
      "$(awk '/^NoNewPrivs:/{print $2}' /proc/self/status)" \
      "$(awk '/^CapEff:/{print $2}' /proc/self/status)" \
      "$(command -v apprise)" \
      "$env_scope" > "$temporary"
    mv "$temporary" "$result"
EOF
  cat >"$home/assistant-only.compose.yml" <<'EOF'
services:
  assistant:
    ports: !reset []
EOF

  assign_fixture_identity "$home" "$uid" "$gid"

  PREPARED_HOME="$home"
  PREPARED_PROJECT="$project"
}

prepare_pre_09_fixture() {
  local uid="$1"
  local gid="$2"
  local home="${SMOKE_ROOT}/pre-09"
  local project_prefix='openpalm-debian-cron-migration'
  local project
  project="$(smoke_guarded_project "${project_prefix}-$$" "$project_prefix" 'generated migration smoke project')"
  smoke_assert_project_absent "$project"

  smoke_copy_skeleton "$home"
  smoke_write_stack_env "$home" "$(smoke_platform_version)" \
    48210 48200 48230 48231 48220 48221 "$uid" "$gid"
  smoke_seed_secrets "$home" 'debian-cron-migration-password'
  smoke_ensure_home_dirs "$home"

  cat >"$home/config/akm/config.json" <<'EOF'
{
  "stashDir": "/stash",
  "semanticSearchMode": "off"
}
EOF
  cat >"$home/knowledge/tasks/pre-09-migration.yml" <<'EOF'
version: 1
schedule: '4 0 31 2 *'
enabled: true
command:
  - /bin/true
EOF
  mkdir -p "$home/knowledge/vaults"
  printf '%s\n' 'PRE_09_STORAGE_CANARY=preserved' >"$home/knowledge/vaults/pre-09.env"
  chmod 700 "$home/knowledge/vaults"
  chmod 600 \
    "$home/config/akm/config.json" \
    "$home/knowledge/tasks/pre-09-migration.yml" \
    "$home/knowledge/vaults/pre-09.env"
  cat >"$home/assistant-only.compose.yml" <<'EOF'
services:
  assistant:
    ports: !reset []
EOF

  assign_fixture_identity "$home" "$uid" "$gid"

  PREPARED_HOME="$home"
  PREPARED_PROJECT="$project"
}

start_fixture() {
  local home="$1"
  local project="$2"
  local failure_message="${3:-Assistant runtime did not pass its health probe}"
  local diagnostic_pattern="${4:-}"
  local diagnostic_message="${5:-$failure_message}"
  local container
  smoke_assert_project_absent "$project"
  SMOKE_HOMES+=("$home")
  SMOKE_PROJECTS+=("$project")
  cron_compose "$home" "$project" up -d assistant >/dev/null
  container="$(cron_compose "$home" "$project" ps -q assistant)"
  [[ -n "$container" ]] || fail "Compose did not create the Assistant container"
  wait_for_runtime "$home" "$project" "$container" "$failure_message" "$diagnostic_pattern" "$diagnostic_message"
  STARTED_CONTAINER="$container"
}

replace_with_legacy_crontab() {
  local container="$1"
  local id="$2"
  local schedule="$3"
  local strip_block
  [[ "$id" =~ ^[a-z0-9-]+$ ]] || fail "unsafe legacy smoke task id: $id"
  strip_block='$0 == begin { skipping=1; begins++; next }
$0 == end { if (!skipping) exit 65; skipping=0; ends++; next }
!skipping { print }
END { if (skipping || begins != ends || begins > 1) exit 65 }'
  timeout 10s docker exec --user root "$container" /bin/bash -c '
    set -euo pipefail
    existing="$(mktemp)"
    temporary="$(mktemp)"
    /usr/bin/crontab -u node -l >"$existing"
    /usr/bin/awk -v begin="# akm:task $1 BEGIN" -v end="# akm:task $1 END" \
      "$3" "$existing" >"$temporary"
    {
      printf "%s\n" "# akm:task $1 BEGIN"
      printf "%s /usr/local/bin/node /opt/openpalm/tools/node_modules/akm-cli/dist/akm tasks run %s >> /opt/akm/cache/tasks/logs/%s.log 2>&1\n" \
        "$2" "$1" "$1"
      printf "%s\n" "# akm:task $1 END"
    } >>"$temporary"
    /usr/bin/crontab -u node "$temporary"
    rm -f "$existing" "$temporary"
  ' _ "$id" "$schedule" "$strip_block"
}

assert_legacy_launcher_binding() {
  local container="$1"
  local id="$2"
  local crontab body
  crontab="$(read_crontab "$container")" || fail "could not read legacy native crontab for task $id"
  body="$(task_body "$crontab" "$id")" || fail "legacy task $id is not one complete native binding"
  [[ "$body" == *'/opt/openpalm/tools/node_modules/akm-cli/dist/akm tasks run '* ]] ||
    fail "task $id does not contain the real package-local pre-0.9 launcher binding"
}

restart_reconstructs_binding() {
  local home="$1"
  local project="$2"
  local container="$3"
  local after
  replace_with_legacy_crontab "$container" cron-binding '* * * * *'
  assert_legacy_launcher_binding "$container" cron-binding
  cron_compose "$home" "$project" restart --timeout 10 assistant >/dev/null
  after="$(cron_compose "$home" "$project" ps -q assistant)"
  [[ "$after" == "$container" ]] || fail "Compose restart unexpectedly recreated the container"
  wait_for_runtime "$home" "$project" "$after"
  assert_task_binding "$after" cron-binding '* * * * *' true
}

recreate_reconstructs_binding() {
  local home="$1"
  local project="$2"
  local container="$3"
  local after
  replace_with_legacy_crontab "$container" cron-binding '* * * * *'
  assert_legacy_launcher_binding "$container" cron-binding
  cron_compose "$home" "$project" up -d --force-recreate --no-deps assistant >/dev/null
  after="$(cron_compose "$home" "$project" ps -q assistant)"
  [[ -n "$after" && "$after" != "$container" ]] || fail "force-recreate did not replace the Assistant container"
  wait_for_runtime "$home" "$project" "$after"
  assert_task_binding "$after" cron-binding '* * * * *' true
  RECREATED_CONTAINER="$after"
}

run_akm_migration_gate() {
  local container="$1"
  local values primary_gid crontab_gid
  values="$(assistant_identity_values "$container")"
  primary_gid="${values%%:*}"
  crontab_gid="${values##*:}"
  timeout 180s docker exec --user root "$container" /usr/bin/setpriv \
    --reuid=node --regid="$primary_gid" --groups="$crontab_gid" \
    --bounding-set=-all --inh-caps=-all --ambient-caps=-all --no-new-privs -- \
    /usr/bin/env -u OPENCODE_SERVER_PASSWORD \
    HOME=/home/opencode USER=node LOGNAME=node SHELL=/bin/bash PATH="$SYSTEM_PATH" \
    /usr/local/lib/openpalm/migrate-akm-09.sh
}

assert_pre_09_migration() {
  local container="$1"
  local uid="$2"
  local gid="$3"
  local akm_version phase owner path root_owned
  akm_version="$(timeout 10s docker exec --user node "$container" /usr/local/bin/akm --version)"
  [[ "$akm_version" == "$EXPECTED_AKM_VERSION" ]] ||
    fail "Assistant runtime AKM version is $akm_version; expected exact $EXPECTED_AKM_VERSION"
  phase="$(timeout 5s docker exec --user node "$container" \
    /bin/cat /opt/akm/state/openpalm-0.9-migration-phase)"
  [[ "$phase" == "1|0.9.0|complete|${akm_version}" ]] ||
    fail "providerless pre-0.9 migration did not reach its completion phase (got: ${phase:-missing})"

  timeout 10s docker exec --user node "$container" /usr/bin/jq -e '
    .configVersion == "0.9.0" and
    (.bundles | type) == "object" and
    (.bundles | length) >= 1 and
    (.defaultBundle | type) == "string" and
    .stashDir == null and
    .semanticSearchMode == "off"
  ' /etc/akm/config.json >/dev/null || fail "AKM did not install a providerless current config"
  timeout 10s docker exec --user node "$container" /usr/bin/jq -e '
    (has("configVersion") | not) and
    .stashDir == "/stash" and
    .semanticSearchMode == "off"
  ' /opt/akm/state/openpalm-pre-0.9-missing-version/config.json >/dev/null ||
    fail "missing-version preflight backup did not preserve the original config"
  [[ "$(timeout 5s docker exec --user node "$container" /bin/cat \
    /opt/akm/state/openpalm-pre-0.9-missing-version/.complete)" == '1|0.9.0' ]] ||
    fail "missing-version preflight backup is not complete"
  timeout 5s docker exec --user node "$container" /bin/sh -eu -c '
    /usr/bin/grep -qx "version: 2" /stash/tasks/pre-09-migration.yml
    ! /usr/bin/grep -q "version: 1" /stash/tasks/pre-09-migration.yml
    /usr/bin/grep -q "/bin/true" /stash/tasks/pre-09-migration.yml
    test "$(/bin/cat /stash/env/pre-09.env)" = "PRE_09_STORAGE_CANARY=preserved"
    test "$(/bin/cat /stash/vaults/pre-09.env)" = "PRE_09_STORAGE_CANARY=preserved"
    test -s /stash/vaults/.migrated
    test -f /opt/akm/data/state.db
  ' || fail "AKM did not migrate the v1 task and legacy storage fixture"
  assert_task_binding "$container" pre-09-migration '4 0 31 2 *' true

  for path in \
    /etc/akm/config.json \
    /stash/tasks/pre-09-migration.yml \
    /stash/env/pre-09.env \
    /stash/vaults/.migrated \
    /opt/akm/data/state.db \
    /opt/akm/state/openpalm-pre-0.9-missing-version/config.json \
    /opt/akm/state/openpalm-pre-0.9-missing-version/.complete \
    /opt/akm/state/openpalm-0.9-migration-phase; do
    owner="$(timeout 5s docker exec --user root "$container" /usr/bin/stat -c %u:%g "$path")"
    [[ "$owner" == "${uid}:${gid}" ]] ||
      fail "migrated artifact $path is not owned by the configured non-root identity (got $owner)"
  done
  root_owned="$(timeout 10s docker exec --user root "$container" /usr/bin/find \
    /etc/akm /stash /opt/akm/cache /opt/akm/data /opt/akm/state \
    \( -uid 0 -o -gid 0 \) -print -quit)"
  [[ -z "$root_owned" ]] || fail "AKM migration left a root-owned mounted artifact: $root_owned"
}

exercise_legacy_launcher_rebind() {
  local home="$1"
  local project="$2"
  local container="$3"
  local akm_version sync_pid crontab phase
  akm_version="$(timeout 10s docker exec --user node "$container" /usr/local/bin/akm --version)"
  [[ "$akm_version" == "$EXPECTED_AKM_VERSION" ]] ||
    fail "Assistant runtime AKM version is $akm_version; expected exact $EXPECTED_AKM_VERSION"
  sync_pid="$(timeout 5s docker exec --user root "$container" /bin/cat /run/openpalm/sync.pid)"
  [[ "$sync_pid" =~ ^[1-9][0-9]*$ ]] || fail "reconciliation monitor PID is malformed: $sync_pid"
  timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -STOP "$1"' _ "$sync_pid"

  replace_with_legacy_crontab "$container" pre-09-migration '4 0 31 2 *'
  assert_legacy_launcher_binding "$container" pre-09-migration
  timeout 5s docker exec --user node "$container" /bin/sh -c \
    'printf "1|0.9.0|post-apply|%s\n" "$1" > /opt/akm/state/openpalm-0.9-migration-phase' \
    _ "$akm_version"
  if ! run_akm_migration_gate "$container"; then
    timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -CONT "$1"' _ "$sync_pid" || true
    cron_compose "$home" "$project" logs assistant --tail 120 >&2 || true
    fail "pinned AKM $akm_version could not rebind the real pre-0.9 launcher fixture"
  fi
  timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -CONT "$1"' _ "$sync_pid"

  phase="$(timeout 5s docker exec --user node "$container" \
    /bin/cat /opt/akm/state/openpalm-0.9-migration-phase)"
  [[ "$phase" == "1|0.9.0|complete|${akm_version}" ]] ||
    fail "rebind post-apply retry did not restore the complete migration phase"
  crontab="$(read_crontab "$container")" || fail "could not read rebound native crontab"
  [[ "$crontab" != *'/opt/openpalm/tools/node_modules/akm-cli/dist/akm'* ]] ||
    fail "legacy package-local AKM launcher survived migration rebind"
  [[ "$crontab" != *' tasks run '* ]] || fail "legacy plural tasks ABI survived migration rebind"
  assert_task_binding "$container" pre-09-migration '4 0 31 2 *' true
  if ! wait_for_health_probe_success "$container" "$HEALTH_RECOVERY_TIMEOUT_SECONDS"; then
    cron_compose "$home" "$project" logs assistant --tail 120 >&2 || true
    fail "Assistant health did not recover after the migration rebind check"
  fi
}

run_pre_09_migration_smoke() {
  local uid=2003
  local gid=2004
  local home project container
  echo "Exercising real pre-0.9 image migration as ${uid}:${gid}..."
  prepare_pre_09_fixture "$uid" "$gid"
  home="$PREPARED_HOME"
  project="$PREPARED_PROJECT"
  start_fixture "$home" "$project" \
    'Pinned image AKM could not migrate the providerless minimal pre-0.9 config/task/storage fixture; inspect the Assistant logs above' \
    'migrations are not an exact ordered prefix' \
    'Pinned image AKM migrated the minimal providerless fixture but its migrator and runtime disagree on released migration checksums'
  container="$STARTED_CONTAINER"
  assert_runtime_identity "$container" "$uid" "$gid"
  assert_pre_09_migration "$container" "$uid" "$gid"
  exercise_legacy_launcher_rebind "$home" "$project" "$container"
}

test_task_reconciliation() {
  local container="$1"
  # Do not call run_task_sync in this matrix: each transition must be observed
  # through the production 60-second reconciliation monitor.
  write_task "$container" cron-matrix.yml <<'EOF'
version: 2
schedule: '1 0 31 2 *'
enabled: true
command:
  - /bin/true
EOF
  wait_for_task_binding "$container" cron-matrix '1 0 31 2 *' true

  write_task "$container" cron-matrix.yml <<'EOF'
version: 2
schedule: '2 0 31 2 *'
enabled: true
command:
  - /bin/true
EOF
  wait_for_task_binding "$container" cron-matrix '2 0 31 2 *' true

  write_task "$container" cron-matrix.yml <<'EOF'
version: 2
schedule: '2 0 31 2 *'
enabled: false
command:
  - /bin/true
EOF
  wait_for_task_binding "$container" cron-matrix '2 0 31 2 *' false

  delete_task "$container" cron-matrix.yml
  wait_for_task_absent "$container" cron-matrix
}

test_reconciliation_failure_recovery() {
  local home="$1"
  local project="$2"
  local container="$3"
  # Recovery likewise remains in-process; only final fixture cleanup uses the
  # one-shot helper after healthy status has been observed.
  wait_for_sync_status "$container" healthy 10
  write_task "$container" invalid-reconciliation.yml <<'EOF'
version: [
EOF
  wait_for_sync_status "$container" degraded
  wait_for_application_runtime "$home" "$project" "$container"
  # Execute the configured probe directly instead of waiting through Docker's
  # five 30-second retries merely to observe the same status predicate.
  if run_health_probe "$container"; then
    fail "Assistant health probe passed while reconciliation was degraded"
  fi

  write_task "$container" invalid-reconciliation.yml <<'EOF'
version: 2
schedule: '3 0 31 2 *'
enabled: true
command:
  - /bin/true
EOF
  wait_for_sync_status "$container" healthy
  if ! run_health_probe "$container"; then
    fail "Assistant health probe did not recover after background reconciliation"
  fi
  assert_task_binding "$container" invalid-reconciliation '3 0 31 2 *' true
  delete_task "$container" invalid-reconciliation.yml
  run_task_sync "$container"
  assert_task_absent "$container" invalid-reconciliation
}

test_reconciliation_monitor_liveness() {
  local home="$1"
  local project="$2"
  local container="$3"
  local sync_pid status
  if ! run_health_probe "$container"; then
    fail "Assistant health probe was not healthy before stopping the reconciliation monitor"
  fi
  sync_pid="$(timeout 5s docker exec --user root "$container" /bin/cat /run/openpalm/sync.pid)"
  [[ "$sync_pid" =~ ^[1-9][0-9]*$ ]] || fail "reconciliation monitor PID is malformed: $sync_pid"
  timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -STOP "$1"' _ "$sync_pid"

  if ! wait_for_health_probe_failure "$container" "$STALE_HEALTH_TIMEOUT_SECONDS"; then
    timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -CONT "$1"' _ "$sync_pid" || true
    cron_compose "$home" "$project" logs assistant --tail 120 >&2 || true
    fail "Assistant health stayed green after the reconciliation monitor stopped"
  fi
  status="$(timeout 5s docker exec --user root "$container" /bin/cat /run/openpalm/task-sync.status)"
  if [[ ! "$status" =~ ^healthy\ [1-9][0-9]*\ ok$ ]] || ! run_application_probe "$container"; then
    timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -CONT "$1"' _ "$sync_pid" || true
    fail "Assistant health failure while the monitor was stopped was not isolated to stale reconciliation status"
  fi

  timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -CONT "$1"' _ "$sync_pid"
  if ! wait_for_health_probe_success "$container" "$HEALTH_RECOVERY_TIMEOUT_SECONDS"; then
    cron_compose "$home" "$project" logs assistant --tail 120 >&2 || true
    fail "Assistant health did not recover after the reconciliation monitor resumed"
  fi
}

test_required_process_death_restart() {
  local home="$1"
  local project="$2"
  local container="$3"
  local process="$4"
  local label="$5"
  local before_count before_started before_logs before_log_count
  local after_count=0 after_started='' running='' after_logs after_log_count
  local deadline=$((SECONDS + 120))
  before_count="$(timeout 5s docker inspect --format '{{.RestartCount}}' "$container")"
  before_started="$(timeout 5s docker inspect --format '{{.State.StartedAt}}' "$container")"
  before_logs="$(cron_compose "$home" "$project" logs --no-color assistant 2>&1)" ||
    fail "could not read Assistant logs before the $label death check"
  before_log_count="$(printf '%s\n' "$before_logs" |
    /usr/bin/grep -cF 'a required Assistant process exited; stopping the container' || true)"
  timeout 5s docker exec --user root "$container" /bin/sh -c \
    'kill -TERM "$(/usr/bin/cat "/run/openpalm/$1.pid")"' _ "$process"

  while ((SECONDS < deadline)); do
    after_count="$(timeout 5s docker inspect --format '{{.RestartCount}}' "$container" 2>/dev/null || printf '0')"
    after_started="$(timeout 5s docker inspect --format '{{.State.StartedAt}}' "$container" 2>/dev/null || true)"
    running="$(timeout 5s docker inspect --format '{{.State.Running}}' "$container" 2>/dev/null || true)"
    if [[ "$after_count" =~ ^[0-9]+$ ]] && ((after_count > before_count)) &&
      [[ "$after_started" != "$before_started" && "$running" == "true" ]]; then
      break
    fi
    sleep 1
  done
  if [[ ! "$after_count" =~ ^[0-9]+$ ]] || ((after_count <= before_count)) ||
    [[ "$after_started" == "$before_started" || "$running" != "true" ]]; then
    fail "$label death did not produce a visible Docker restart"
  fi
  wait_for_runtime "$home" "$project" "$container"
  after_logs="$(cron_compose "$home" "$project" logs --no-color assistant 2>&1)" ||
    fail "could not read Assistant logs after the $label death check"
  after_log_count="$(printf '%s\n' "$after_logs" |
    /usr/bin/grep -cF 'a required Assistant process exited; stopping the container' || true)"
  if [[ ! "$before_log_count" =~ ^[0-9]+$ || ! "$after_log_count" =~ ^[0-9]+$ ]] ||
    ((after_log_count <= before_log_count)); then
    fail "$label death was not visible in Assistant logs"
  fi
  assert_task_binding "$container" cron-binding '* * * * *' true
}

test_active_child_shutdown() {
  local home="$1"
  local project="$2"
  local container="$3"
  local child_pid
  write_task "$container" shutdown-child.yml <<'EOF'
version: 2
schedule: '* * * * *'
enabled: true
timeoutMs: 300000
command:
  - /bin/bash
  - -c
  - |
    trap 'printf terminated > /work/shutdown-child-terminated; exit 0' TERM INT HUP
    printf '%s' "$$" > /work/shutdown-child-pid
    printf started > /work/shutdown-child-started
    while :; do
      sleep 1
    done
EOF
  run_task_sync "$container"
  assert_task_binding "$container" shutdown-child '* * * * *' true
  wait_for_file_content "$home/workspace/shutdown-child-started" started "$CRON_EXECUTION_TIMEOUT_SECONDS"
  child_pid="$(<"$home/workspace/shutdown-child-pid")"
  [[ "$child_pid" =~ ^[1-9][0-9]*$ ]] || fail "active scheduled child PID is malformed: $child_pid"
  timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -0 "$1"' _ "$child_pid" ||
    fail "scheduled child exited before the shutdown test"
  delete_task "$container" shutdown-child.yml
  run_task_sync "$container"
  assert_task_absent "$container" shutdown-child
  timeout 5s docker exec --user root "$container" /bin/sh -c 'kill -0 "$1"' _ "$child_pid" ||
    fail "removing the task stopped the already-active scheduled child"
  cron_compose "$home" "$project" stop --timeout 10 assistant >/dev/null
  wait_for_file_content "$home/workspace/shutdown-child-terminated" terminated
}

run_identity_pair() {
  local uid="$1"
  local gid="$2"
  local full_matrix="$3"
  local home project container crontab expected_result

  echo "Exercising Debian cron runtime as ${uid}:${gid}..."
  prepare_fixture "$uid" "$gid"
  home="$PREPARED_HOME"
  project="$PREPARED_PROJECT"
  start_fixture "$home" "$project"
  container="$STARTED_CONTAINER"
  assert_runtime_identity "$container" "$uid" "$gid"
  if [[ "$full_matrix" == "1" ]]; then
    echo 'Checking the image-default healthcheck command at runtime...'
    run_image_health_probe "$container" || fail "Assistant image-default healthcheck command failed at runtime"
  fi
  assert_task_binding "$container" cron-binding '* * * * *' true
  crontab="$(read_crontab "$container")"
  [[ "$crontab" != *'OPENPALM_CRON_ENV_LEAK_CANARY'* ]] ||
    fail "knowledge/env/user.env leaked into the native crontab"
  printf -v expected_result \
    'uid=%s\ngid=%s\ngroups=%s\nno_new_privs=1\ncap_eff=0000000000000000\napprise=/opt/assistant-tools/bin/apprise\nenv_scope=absent' \
    "$uid" "$gid" "$gid"
  wait_for_file_content "$home/workspace/cron-binding-result" "$expected_result" \
    "$CRON_EXECUTION_TIMEOUT_SECONDS"

  if [[ "$full_matrix" == "1" ]]; then
    echo 'Checking background add/edit/disable/delete reconciliation...'
    test_task_reconciliation "$container"
    echo 'Checking restart and fresh-container reconstruction...'
    restart_reconstructs_binding "$home" "$project" "$container"
    recreate_reconstructs_binding "$home" "$project" "$container"
    container="$RECREATED_CONTAINER"
    assert_runtime_identity "$container" "$uid" "$gid"
    echo 'Checking reconciliation health failure and recovery...'
    test_reconciliation_failure_recovery "$home" "$project" "$container"
    echo 'Checking reconciliation monitor stale-health detection and recovery...'
    test_reconciliation_monitor_liveness "$home" "$project" "$container"
    echo 'Checking reconciliation monitor death visibility and automatic recovery...'
    test_required_process_death_restart "$home" "$project" "$container" sync 'reconciliation monitor'
    echo 'Checking cron death visibility and automatic recovery...'
    test_required_process_death_restart "$home" "$project" "$container" cron cron
    echo 'Checking shutdown propagation to an active scheduled child...'
    test_active_child_shutdown "$home" "$project" "$container"
  fi
}

assert_image_freshness() {
  local host_entrypoint host_migration host_prepare image_output hash path
  local image_entrypoint=''
  local image_migration=''
  local image_prepare=''
  host_entrypoint="$(sha256sum containers/assistant/entrypoint.sh)"
  host_entrypoint="${host_entrypoint%% *}"
  host_migration="$(sha256sum containers/assistant/migrate-akm-09.sh)"
  host_migration="${host_migration%% *}"
  host_prepare="$(sha256sum containers/assistant/prepare-akm-09-config.mjs)"
  host_prepare="${host_prepare%% *}"
  image_output="$(timeout 30s docker run --rm --entrypoint /usr/bin/sha256sum openpalm/assistant:dev \
    /usr/local/bin/opencode-entrypoint.sh \
    /usr/local/lib/openpalm/migrate-akm-09.sh \
    /usr/local/lib/openpalm/prepare-akm-09-config.mjs)" ||
    fail 'could not hash cron runtime files in the prebuilt Assistant image; rebuild the image'
  while read -r hash path; do
    case "$path" in
      /usr/local/bin/opencode-entrypoint.sh) image_entrypoint="$hash" ;;
      /usr/local/lib/openpalm/migrate-akm-09.sh) image_migration="$hash" ;;
      /usr/local/lib/openpalm/prepare-akm-09-config.mjs) image_prepare="$hash" ;;
    esac
  done <<<"$image_output"
  [[ -n "$image_entrypoint" && "$image_entrypoint" == "$host_entrypoint" ]] ||
    fail 'prebuilt Assistant entrypoint does not exactly match the working tree; rebuild the image'
  [[ -n "$image_migration" && "$image_migration" == "$host_migration" ]] ||
    fail 'prebuilt Assistant migration helper does not exactly match the working tree; rebuild the image'
  [[ -n "$image_prepare" && "$image_prepare" == "$host_prepare" ]] ||
    fail 'prebuilt Assistant migration config preparer does not exactly match the working tree; rebuild the image'
}

command -v docker >/dev/null || fail 'Docker is required for the Debian cron behavior smoke'
command -v jq >/dev/null || fail 'jq is required for the Debian cron behavior smoke'
command -v sha256sum >/dev/null || fail 'sha256sum is required for the Debian cron behavior smoke'
command -v timeout >/dev/null || fail 'GNU timeout is required for the Debian cron behavior smoke'
timeout 30s docker info >/dev/null
smoke_build_images assistant
assert_image_freshness
smoke_create_guarded_home "$ROOT_DIR" "$SMOKE_ROOT" '.debian-cron-smoke' OP_DEBIAN_CRON_SMOKE_HOME
SMOKE_ROOT_CREATED=1

run_identity_pair 2001 2002 1
run_identity_pair 1000 1000 0
run_pre_09_migration_smoke

SMOKE_COMPLETED=1
