#!/usr/bin/env bash
set -euo pipefail

usage() {
	cat <<'EOF'
Usage: scripts/dev-setup.sh [--seed-env] [--force]

Creates local .dev directories and seeds dev config files.

Options:
  --seed-env   Copy core/assets/secrets.env to .dev/config/secrets.env if missing,
               and generate STATE_HOME/artifacts/stack.env with auto-detected values.
  --force      Overwrite seeded files even if they already exist.
  -h, --help   Show this help
EOF
}

seed_env=0
force=0

for arg in "$@"; do
	case "$arg" in
	--seed-env) seed_env=1 ;;
	--force) force=1 ;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "Unknown option: $arg" >&2
		usage >&2
		exit 1
		;;
	esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV_ROOT="$ROOT_DIR/.dev"

CONFIG_DIR="$DEV_ROOT/config/assistant"
CHANNELS_DIR="$DEV_ROOT/config/channels"
STATE_DIR="$DEV_ROOT/state"
DATA_DIR="$DEV_ROOT/data"

CADDY_SRC="$ROOT_DIR/core/assets/Caddyfile"
CADDY_CORE_DEST="$DATA_DIR/caddy/Caddyfile"
COMPOSE_SRC="$ROOT_DIR/core/assets/docker-compose.yml"
COMPOSE_CORE_DEST="$DATA_DIR/docker-compose.yml"
ENV_SRC="$ROOT_DIR/core/assets/secrets.env"
ENV_DEST="$DEV_ROOT/config/secrets.env"
STACK_ENV_DATA="$DATA_DIR/stack.env"
STACK_ENV_DEST="$STATE_DIR/artifacts/stack.env"
mkdir -p "$CONFIG_DIR" "$CHANNELS_DIR" "$DEV_ROOT/config/automations" \
	"$STATE_DIR/artifacts" "$STATE_DIR/audit" "$STATE_DIR/automations" "$STATE_DIR/opencode" \
	"$DATA_DIR/openmemory" \
	"$DATA_DIR/assistant" "$DATA_DIR/guardian" \
	"$DATA_DIR/caddy/data" "$DATA_DIR/caddy/config" \
	"$DATA_DIR/automations" "$DATA_DIR/opencode"

# Seed core assets to DATA_HOME (source of truth) — write-once unless --force
if [[ ! -f "$CADDY_CORE_DEST" || $force -eq 1 ]]; then
	cp "$CADDY_SRC" "$CADDY_CORE_DEST"
fi
if [[ ! -f "$COMPOSE_CORE_DEST" || $force -eq 1 ]]; then
	cp "$COMPOSE_SRC" "$COMPOSE_CORE_DEST"
fi

# Bootstrap staging: always copy to STATE so compose works before admin's first apply
cp "$COMPOSE_CORE_DEST" "$STATE_DIR/artifacts/docker-compose.yml"
cp "$CADDY_CORE_DEST" "$STATE_DIR/artifacts/Caddyfile"

if [[ $seed_env -eq 1 ]]; then
	# ── User secrets (CONFIG_HOME) ─────────────────────────────────────
	# Only contains ADMIN_TOKEN and LLM provider keys. No paths or infra config.
	if [[ ! -f "$ENV_DEST" || $force -eq 1 ]]; then
		cp "$ENV_SRC" "$ENV_DEST"
	fi

	# ── System stack config (STATE_HOME/artifacts/stack.env) ──────────
	# Auto-detected infrastructure config — paths, UID/GID, image, networking,
	# and channel HMAC secrets. The admin regenerates this on every apply;
	# dev-setup.sh seeds it so the full stack can start before the admin
	# has run for the first time.
	if [[ ! -f "$STACK_ENV_DATA" || $force -eq 1 ]]; then
		uid=$(id -u)
		gid=$(id -g)

		# Detect Docker socket path from the active docker context (supports
		# OrbStack, Colima, Rancher Desktop, etc.)
		docker_sock="/var/run/docker.sock"
		if host_url="$(docker context inspect --format '{{.Endpoints.docker.Host}}' 2>/dev/null)"; then
			case "$host_url" in
			unix://*)
				detected_sock="${host_url#unix://}"
				if [[ -S "$detected_sock" ]]; then
					docker_sock=$detected_sock
				fi
				;;
			esac
		fi

		cat >"$STACK_ENV_DATA" <<EOF
# OpenPalm Stack Configuration — system-managed, do not edit
# Generated by scripts/dev-setup.sh. Overwritten by admin on each apply.

# ── XDG Paths ──────────────────────────────────────────────────────
OPENPALM_CONFIG_HOME=$DEV_ROOT/config
OPENPALM_DATA_HOME=$DEV_ROOT/data
OPENPALM_STATE_HOME=$DEV_ROOT/state
OPENPALM_WORK_DIR=$DEV_ROOT/work

# ── User/Group ──────────────────────────────────────────────────────
OPENPALM_UID=$uid
OPENPALM_GID=$gid

# ── Docker Socket ───────────────────────────────────────────────────
OPENPALM_DOCKER_SOCK=$docker_sock

# ── Images ──────────────────────────────────────────────────────────
OPENPALM_IMAGE_NAMESPACE=openpalm
OPENPALM_IMAGE_TAG=latest

# ── Networking ──────────────────────────────────────────────────────
OPENPALM_INGRESS_BIND_ADDRESS=127.0.0.1
OPENPALM_INGRESS_PORT=8080

# ── OpenMemory ──────────────────────────────────────────────────────
OPENMEMORY_DASHBOARD_API_URL=http://localhost:8765
OPENMEMORY_USER_ID=default_user

# ── Channel HMAC Secrets ─────────────────────────────────────────────
# Generated by admin when channels are installed. Empty on initial setup.
EOF
	fi

	# Stage to STATE_HOME/artifacts/ for compose consumption
	# Runs outside the conditional so clearing .dev/state is recovered
	if [[ -f "$STACK_ENV_DATA" ]]; then
		cp "$STACK_ENV_DATA" "$STACK_ENV_DEST"
	fi

fi

# ── Seed OpenMemory default config ──────────────────────────────────────
if [ ! -f "$DATA_DIR/openmemory/default_config.json" ]; then
	cat > "$DATA_DIR/openmemory/default_config.json" << 'OMEOF'
{
  "mem0": {
    "llm": {
      "provider": "openai",
      "config": {
        "model": "gpt-4o-mini",
        "temperature": 0.1,
        "max_tokens": 2000,
        "api_key": "env:OPENAI_API_KEY"
      }
    },
    "embedder": {
      "provider": "openai",
      "config": {
        "model": "text-embedding-3-small",
        "api_key": "env:OPENAI_API_KEY"
      }
    },
    "vector_store": {
      "provider": "qdrant",
      "config": {
        "collection_name": "openmemory",
        "path": "/data/qdrant",
        "embedding_model_dims": 1536
      }
    }
  },
  "openmemory": {
    "custom_instructions": ""
  }
}
OMEOF
fi

# ── Seed OpenMemory patched memory.py ─────────────────────────────────────
# The upstream openmemory-mcp image hardcodes host-based Qdrant config.
# This patched memory.py reads vector_store config from default_config.json,
# enabling embedded (file-based) Qdrant via the `path` key.
if [[ ! -f "$DATA_DIR/openmemory/memory.py" || $force -eq 1 ]]; then
	cp "$ROOT_DIR/core/assets/openmemory-memory.py" "$DATA_DIR/openmemory/memory.py"
fi

if [[ $EUID -ne 0 ]]; then
	chown -R "$(id -u):$(id -g)" "$DATA_DIR" "$CONFIG_DIR" "$CHANNELS_DIR" "$STATE_DIR"
else
	echo "Note: running as root; ownership left as-is." >&2
fi

echo "Dev setup complete."
