#!/usr/bin/env bash
set -euo pipefail

usage() {
	cat <<'EOF'
Usage: scripts/dev-setup.sh [--seed-env] [--force]

Creates local .dev directories and seeds dev config files.

Options:
  --seed-env   Copy assets/secrets.env to .dev/config/secrets.env if missing,
               and generate STATE_HOME/artifacts/stack.env with auto-detected values.
  --force      Overwrite seeded files even if they already exist.
  -h, --help   Show this help
EOF
}

seed_env=0
force=0

for arg in "$@"; do
	case "$arg" in
	--seed-env) seed_env=1 ;;
	--force) force=1 ;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "Unknown option: $arg" >&2
		usage >&2
		exit 1
		;;
	esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV_ROOT="$ROOT_DIR/.dev"

CONFIG_DIR="$DEV_ROOT/config/opencode"
CHANNELS_DIR="$DEV_ROOT/config/channels"
STATE_DIR="$DEV_ROOT/state"
DATA_DIR="$DEV_ROOT/data"

CADDY_SRC="$ROOT_DIR/assets/Caddyfile"
CADDY_CORE_DEST="$DATA_DIR/caddy/Caddyfile"
CADDY_STAGE_DEST="$STATE_DIR/artifacts/Caddyfile"
ENV_SRC="$ROOT_DIR/assets/secrets.env"
ENV_DEST="$DEV_ROOT/config/secrets.env"
STACK_ENV_DATA="$DATA_DIR/stack.env"
STACK_ENV_DEST="$STATE_DIR/artifacts/stack.env"
ADMIN_ENV_DEST="$ROOT_DIR/core/admin/.env"

mkdir -p "$CONFIG_DIR" "$CHANNELS_DIR" \
	"$STATE_DIR/artifacts" "$STATE_DIR/audit" \
	"$DATA_DIR/postgres" "$DATA_DIR/qdrant" "$DATA_DIR/openmemory" \
	"$DATA_DIR/assistant" "$DATA_DIR/guardian" \
	"$DATA_DIR/caddy/data" "$DATA_DIR/caddy/config"

if [[ ! -f "$CADDY_CORE_DEST" || $force -eq 1 ]]; then
	cp "$CADDY_SRC" "$CADDY_CORE_DEST"
fi

if [[ ! -f "$CADDY_STAGE_DEST" || $force -eq 1 ]]; then
	cp "$CADDY_CORE_DEST" "$CADDY_STAGE_DEST"
fi

if [[ $seed_env -eq 1 ]]; then
	# ── User secrets (CONFIG_HOME) ─────────────────────────────────────
	# Only contains ADMIN_TOKEN and LLM provider keys. No paths or infra config.
	if [[ ! -f "$ENV_DEST" || $force -eq 1 ]]; then
		cp "$ENV_SRC" "$ENV_DEST"
	fi

	# ── System stack config (STATE_HOME/artifacts/stack.env) ──────────
	# Auto-detected infrastructure config — paths, UID/GID, image, networking,
	# database password, and channel HMAC secrets. The admin regenerates this
	# on every apply; dev-setup.sh seeds it so the full stack can start before
	# the admin has run for the first time.
	if [[ ! -f "$STACK_ENV_DATA" || $force -eq 1 ]]; then
		uid=$(id -u)
		gid=$(id -g)

		# Auto-detect Docker socket GID
		docker_gid=$gid
		docker_sock="/var/run/docker.sock"

		# Detect socket path from the active docker context (supports
		# OrbStack, Colima, Rancher Desktop, etc.)
		if host_url="$(docker context inspect --format '{{.Endpoints.docker.Host}}' 2>/dev/null)"; then
			case "$host_url" in
			unix://*)
				detected_sock="${host_url#unix://}"
				if [[ -S "$detected_sock" ]]; then
					docker_sock=$detected_sock
				fi
				;;
			esac
		fi

		if [[ -S "$docker_sock" ]]; then
			detected=$(stat -c '%g' "$docker_sock" 2>/dev/null || true)
			if [[ -n "$detected" && "$detected" != "0" ]]; then
				docker_gid=$detected
			fi
		fi

		# Generate a random POSTGRES_PASSWORD — required by compose before admin runs
		postgres_password=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p -c 32)

		cat >"$STACK_ENV_DATA" <<EOF
# OpenPalm Stack Configuration — system-managed, do not edit
# Generated by scripts/dev-setup.sh. Overwritten by admin on each apply.

# ── XDG Paths ──────────────────────────────────────────────────────
OPENPALM_CONFIG_HOME=$DEV_ROOT/config
OPENPALM_DATA_HOME=$DEV_ROOT/data
OPENPALM_STATE_HOME=$DEV_ROOT/state
OPENPALM_WORK_DIR=$HOME/openpalm

# ── User/Group ──────────────────────────────────────────────────────
OPENPALM_UID=$uid
OPENPALM_GID=$gid
OPENPALM_DOCKER_GID=$docker_gid

# ── Docker Socket ───────────────────────────────────────────────────
OPENPALM_DOCKER_SOCK=$docker_sock

# ── Images ──────────────────────────────────────────────────────────
OPENPALM_IMAGE_NAMESPACE=openpalm
OPENPALM_IMAGE_TAG=latest

# ── Networking ──────────────────────────────────────────────────────
OPENPALM_INGRESS_BIND_ADDRESS=127.0.0.1
OPENPALM_INGRESS_PORT=8080

# ── OpenMemory ──────────────────────────────────────────────────────
OPENMEMORY_DASHBOARD_API_URL=http://localhost:8765
OPENMEMORY_USER_ID=default_user

# ── Database ─────────────────────────────────────────────────────────
# Generated once by dev-setup.sh; admin takes ownership after first apply.
POSTGRES_PASSWORD=$postgres_password

# ── Channel HMAC Secrets ─────────────────────────────────────────────
# Generated by admin when channels are installed. Empty on initial setup.
EOF
	fi

	# Stage to STATE_HOME/artifacts/ for compose consumption
	# Runs outside the conditional so clearing .dev/state is recovered
	if [[ -f "$STACK_ENV_DATA" ]]; then
		cp "$STACK_ENV_DATA" "$STACK_ENV_DEST"
	fi

	# ── Admin dev server env (core/admin/.env) ─────────────────────────
	# SvelteKit loads .env automatically in dev mode. This gives the admin
	# dev server the same OPENPALM_* paths it would get in Docker via compose.
	if [[ ! -f "$ADMIN_ENV_DEST" || $force -eq 1 ]]; then
		cat >"$ADMIN_ENV_DEST" <<EOF
# Admin dev server environment — generated by scripts/dev-setup.sh
# Loaded automatically by SvelteKit (vite) in development mode.
# Do not commit this file; it is gitignored.
OPENPALM_CONFIG_HOME=$DEV_ROOT/config
OPENPALM_DATA_HOME=$DEV_ROOT/data
OPENPALM_STATE_HOME=$DEV_ROOT/state
EOF
	fi
fi

if [[ $EUID -ne 0 ]]; then
	chown -R "$(id -u):$(id -g)" "$DATA_DIR" "$CONFIG_DIR" "$CHANNELS_DIR" "$STATE_DIR"
else
	echo "Note: running as root; ownership left as-is." >&2
fi

echo "Dev setup complete."
