// Repo hygiene guard (fable-remediation-plan 1.6): `packages/electron/dist/` is a
// build artifact regenerated by `bun run --cwd packages/electron bundle` (and
// refreshed in CI before the thin-harness boundary check runs). It must never be
// git-tracked — a tracked stale bundle is silent review noise (e.g. a contributor
// grepping the repo for a removed symbol gets a false hit from a stale compiled
// file) and gitignore already declares it ignored, so tracking it is pure drift.
//
// Run via vitest (Node): bun run --cwd packages/electron test
import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '../../..');

describe('packages/electron/dist is not git-tracked', () => {
  it('.gitignore excludes packages/electron/dist/', () => {
    const gitignore = readFileSync(resolve(REPO_ROOT, '.gitignore'), 'utf-8');
    expect(gitignore).toContain('packages/electron/dist/');
  });

  it('git tracks zero files under packages/electron/dist/', () => {
    const tracked = execFileSync('git', ['ls-files', 'packages/electron/dist'], {
      cwd: REPO_ROOT,
      encoding: 'utf-8',
    }).trim();
    expect(tracked).toBe('');
  });
});
