// Repo hygiene guard: the electron build-artifact
// dirs `packages/electron/dist/` and `packages/electron/admin-tools/dist/` are
// regenerated by `bun run --cwd packages/electron bundle` (which builds
// admin-tools first, then main.js/preload.cjs) — the release workflow rebuilds
// both before packaging/publish. They must never be git-tracked: a tracked stale
// bundle is silent review noise (e.g. a contributor grepping the repo for a
// removed symbol gets a false hit from a stale compiled file), and gitignore
// already declares them ignored, so tracking them is pure drift.
//
// Run via vitest (Node): bun run --cwd packages/electron test
import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '../../..');

describe('electron build-artifact dirs are not git-tracked', () => {
  const BUILD_DIRS = ['packages/electron/dist/', 'packages/electron/admin-tools/dist/'];

  for (const dir of BUILD_DIRS) {
    it(`.gitignore excludes ${dir}`, () => {
      const gitignore = readFileSync(resolve(REPO_ROOT, '.gitignore'), 'utf-8');
      expect(gitignore).toContain(dir);
    });

    it(`git tracks zero files under ${dir}`, () => {
      const tracked = execFileSync('git', ['ls-files', dir], {
        cwd: REPO_ROOT,
        encoding: 'utf-8',
      }).trim();
      expect(tracked).toBe('');
    });
  }
});

describe('Electron chat surface', () => {
  it('does not import, update, start, or stop the client SPA', () => {
    const mainSource = readFileSync(resolve(REPO_ROOT, 'packages/electron/src/main.ts'), 'utf-8');

    expect(mainSource).not.toContain('resolveClientBuildDir');
    expect(mainSource).not.toContain('checkAndUpdateClientBuild');
    expect(mainSource).not.toContain('startClientAppServer');
    expect(mainSource).not.toContain('stopClientAppServer');
    expect(mainSource).not.toContain('OP_HOST_CLIENT_PORT');
  });
});

describe('Electron starts independently of Docker', () => {
  const mainSource = readFileSync(resolve(REPO_ROOT, 'packages/electron/src/main.ts'), 'utf-8');
  const preloadSource = readFileSync(resolve(REPO_ROOT, 'packages/electron/src/preload.ts'), 'utf-8');
  const boundarySource = readFileSync(resolve(REPO_ROOT, 'scripts/validate-thin-harness-boundary.sh'), 'utf-8');

  it('has no startup Docker probe or wait', () => {
    expect(mainSource).not.toContain('ensureDockerReady');
    expect(mainSource).not.toContain('DockerPreflight');
    expect(mainSource).not.toContain('checkDocker');
  });

  it('removes the dead preflight IPC and assets', () => {
    expect(mainSource).not.toContain('retry-docker-preflight');
    expect(preloadSource).not.toContain('retryDockerPreflight');
    expect(preloadSource).not.toContain('openDockerInstall');
    expect(existsSync(resolve(REPO_ROOT, 'packages/electron/src/docker-preflight.ts'))).toBe(false);
    expect(existsSync(resolve(REPO_ROOT, 'packages/electron/assets/docker-error.html'))).toBe(false);
  });

  it('removes Docker probes from the thin-harness source allowlist', () => {
    expect(boundarySource).not.toContain('checkDocker');
    expect(boundarySource).not.toContain('checkDockerCompose');
  });

  it('snapshots install materialization before any skeleton refresh', () => {
    const snapshot = mainSource.indexOf('hasMaterializedLocalInstall(homeDir)');
    const refresh = mainSource.indexOf('checkAndUpdateSkeleton(');
    expect(snapshot).toBeGreaterThan(-1);
    expect(refresh).toBeGreaterThan(snapshot);
    expect(mainSource).toMatch(/if \(localInstallWasMaterialized\)[\s\S]*checkAndUpdateSkeleton\(/);
  });

  it('uses the authoritative lib predicate instead of a harness-local classifier', () => {
    expect(existsSync(resolve(REPO_ROOT, 'packages/electron/src/install-snapshot.ts'))).toBe(false);
    expect(mainSource).toMatch(
      /import\s*\{[\s\S]*hasMaterializedLocalInstall[\s\S]*\}\s*from\s*'@openpalm\/lib'/,
    );
    expect(mainSource).not.toContain("from './install-snapshot.js'");
  });
});
